### ISSUE TITLE
Follows from span not tracked in multithreaded runtime.

### ISSUE THREAD

**Issue by mTsBucy1** [tokio-rs/tracing-opentelemetry#183]
### Version
`tracing-opentelemetry: 0.25.0 / 0.27.0` (elaborated below),
`tracing: 0.1.40`

### Platform

`Linux mtstestclient03 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

### Description

I have this scenario in my code:
1. I spawn (multiple) task, which loops and call async instrumented function.
2. this function gets its `tracing::Span::current().id()` and sends it through a tokio mpsc channel.
3. Another task reads this, spawns a instrumented async function, which follows from the received id.

Suddenly my code paniced on startup with 
```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-opentelemetry-0.25.0/src/layer.rs:953:18:
Missing otel data span extensions
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/registry/sharded.rs:437:58:
Mutex poisoned: PoisonError { .. }
[stack trace...]
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
```
This happened here in the code https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.25.0/src/layer.rs#L953.
So far, this hasn't happened again.

I wrote a test, now on the current branch (0.27.0), to try to replicate this behaviour, but it also didn't show the same panic. However, I noticed another odd behaviour: The asserted count fails for a `tokio new_multi_thread` runtime, but succeeds with the `tokio new_current_thread` one. I am not sure whether these are indeed related, but it seems to be a bug in its own right.

```rust
// in tests/follows_from.rs

#[test]
fn trace_follows_from_diff_thread() {
    use tokio::sync::mpsc;

    #[tracing::instrument]
    async fn span_follows_this(chan: &mpsc::Sender<Option<tracing::Id>>) {
        chan.send(tracing::Span::current().id())
            .await
            .expect("Channel should be open");
    }

    #[tracing::instrument(follows_from = [cause])]
    async fn span(cause: Option<tracing::Id>) {}

    async fn receiver(mut chan: mpsc::Receiver<Option<tracing::Id>>) {
        while let Some(cause) = chan.recv().await {
            span(cause).await;
        }
    }

    let (_tracer, provider, exporter, subscriber) = test_tracer();

    tracing::subscriber::with_default(subscriber, || {
        tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(async {
                let (tx, rx) = mpsc::channel(4);
                tokio::spawn(receiver(rx));
                span_follows_this(&tx).await;
                tokio::time::sleep(std::time::Duration::from_millis(10)).await;
                drop(tx);
            })
    });

    drop(provider); // flush all spans
    let spans = exporter.0.lock().unwrap();
    // The follower and followee
    assert_eq!(spans.len(), 2);
}
```

**Comment by mTsBucy1** [comment]
To update this, I think I have figured out why this happens:

In `layer.rs`:
```rust
fn on_follows_from(&self, id: &Id, follows: &Id, ctx: Context<S>) {
    let span = ctx.span(id).expect("Span not found, this is a bug");
    let mut extensions = span.extensions_mut();
    let data = extensions
        .get_mut::<OtelData>()
        .expect("Missing otel data span extensions"); // this is fine

    if let Some(follows_span) = ctx.span(follows) {
        let mut follows_extensions = follows_span.extensions_mut();
        let follows_data = follows_extensions
            .get_mut::<OtelData>()
            .expect("Missing otel data span extensions"); // this panics!!
        }
        ...
    }
}
```

The problem arises when the `on_close` on the `follows` has already been called, and thus the extension removed, but the `Registry` has not yet called `tracing_subscriber::registry::shared::CloseGuard::Drop`, which removes the span for the `LookupSpan` trait.
This can happen as a race condition when another thread closes the `follows` span, and another layer is still processing their `on_close`. I have added a test in my fork and will propose a PR.

**Comment by mladedav** [comment]
I'm happy to remove the panic (because a library like this shouldn't really panic ever), but you should not completely rely on that fix. Instead of sending just the span ID, you should send a clone of the original span. That will make sure that the correct span still exists when you need it. With your fix here, your spans will be missing some information 1/40 times which will usually be better than a panic, but you're still missing telemetry that you're explicitly trying to collect.

Worse still, in both the current and your version, the registry is free to reuse the span ID before you call `follows_from` and you might get there a completely random span.

**Comment by mTsBucy1** [comment]
Okay fair point, the examples and documentation on how to use `follows_from` is quite lacking imo in the tracing ecosystem. I am just going to link [this here](https://docs.rs/tracing/latest/tracing/trait.Subscriber.html#tymethod.new_span) for anyone else (or me in the future), which describes the span ID behaviour.

So the initiator span would not be able to be closed, only exited before the following span?

**Comment by mladedav** [comment]
[Here](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/registry/struct.Registry.html#span-id-generation) is also the documentation to `Registry`, which is pretty much always the actual implementation.

Yes, as long as you hold a `Span`, it will not be closed (because you might still enter it). Once you drop all instances, it will be closed and deleted from the registry, so all `span::Id`s you're still holding are kind of dangling pointers.
